
name: sphinx

on:
  pull_request:
    branches: [ devel ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # for examples, see https://github.com/ammaraskar/sphinx-action-test/blob/master/.github/workflows/default.yml
    - uses: ammaraskar/sphinx-action@0.4
      with:
        docs-folder: "doc/"
        # build-command: # optional, default is make html
        # pre-build-command: # optional
